;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Character.Enemy.EliteRavager",DevComment="")
+GameplayTagList=(Tag="Character.Enemy.Ravager",DevComment="")
+GameplayTagList=(Tag="Character.Enemy.Sentry",DevComment="")
+GameplayTagList=(Tag="Part.Slot.Arm",DevComment="")
+GameplayTagList=(Tag="Part.Slot.Body",DevComment="")
+GameplayTagList=(Tag="Part.Slot.Leg",DevComment="")
+GameplayTagList=(Tag="Character.Enemy.TitanWalker",DevComment="Stage 1 보스: 이동형 공성 병기 ")
+GameplayTagList=(Tag="UI.Goods.RunIn",DevComment="")
+GameplayTagList=(Tag="UI.Goods.RunOut",DevComment="")

